---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# describedata

<!-- badges: start -->
<!-- badges: end -->

This package contains functions written to replicate certain data analysis actions that I've found helpful in biostatistical and epidemiological research. It also contains R replicas of some functions from SAS and Stata to conduct similar analyses and display the results in a similar manner to the functions of those programs. Note that there has not been a concerted effort to fully replicate those all aspects of these functions - more functionality may be added on in the future but the current focus has been on aspects of the functions that have seemed most useful. If there is additional functionality you'd like to see included, please submit an issue on [GitHub](https://github.com/craigjmcgowan/describedata).

## Installation

You can install the released version of describedata from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("describedata")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("craigjmcgowan/describedata")
```

